#!/bin/sh

# Path to molecules.git dir
ROGENTOS_MOLECULE_HOME="${ROGENTOS_MOLECULE_HOME:-/sabayon}"
export ROGENTOS_MOLECULE_HOME

# rootfs and bootfs tarball is generated by beaglebone image
export MAKE_TARBALL="0"
exec "${ROGENTOS_MOLECULE_HOME}"/scripts/mkloopcard.sh "${ROGENTOS_MOLECULE_HOME}"/scripts/mkloopcard_beagleboard_xm_chroot_hook.sh "$@"
