#!/bin/sh

# Path to molecules.git dir
KOGAION_MOLECULE_HOME="${KOGAION_MOLECULE_HOME:-/sabayon}"
export KOGAION_MOLECULE_HOME

# rootfs and bootfs tarball is generated by beaglebone image
export MAKE_TARBALL="0"
export FIRST_PARTITION_OFFSET="5120000"  # 5Mb
export SD_FUSE="${KOGAION_MOLECULE_HOME}/boot/arm/odroid-u2-x2/sd_fuse/sd_fusing.sh"
exec "${KOGAION_MOLECULE_HOME}"/scripts/mkloopcard.sh "${KOGAION_MOLECULE_HOME}"/scripts/mkloopcard_beagleboard_xm_chroot_hook.sh "$@"
